spring.datasource.url=${DB_URL:jdbc:mariadb://57.129.1.54:3306/lologol_db?createDatabaseIfNotExist=true}
# Credenciales
spring.datasource.username=${DB_USER:lologol_257354}
spring.datasource.password=${DB_PASS:n0m3h4g4sBRUTEF0Rc3!:-(}
# Driver MariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Configuracion de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

